# basic-cad-deIII

We are creating a caster.

---
## Table of Contents
* [Table of Contents](#Table-of-Contents)
* [Base](#Base)
* [Mount](#Mount)
* [Fork](#Fork)
* [Tire](#Tire)
* [Wheel](#Wheel)
* [AxleCollarBearings](#AxleCollarBearings)

## Base

### Description

The first assignment is to create the caster base.  The base's dimensions are 200 mm x 120 mm and 8 mm thick.  It has 6 holes 10 mm wide and 20 mm from the edge equally spaced along the edges.

### Evidence
[The Base in Onshape](https://cvilleschools.onshape.com/documents/0d70f655203ca304cb3c5b7d/w/f55603f962f6fc74f5548a68/e/41d730c570a8d75fce9f51b6)

### Image

<img src="https://github.com/OneCHSEngr/BasicCAD/blob/master/images/Base.jpg?raw=true" alt="The Base" width="300">

### Reflection

This was my first Onshape part and [following along with Dr. Shields made it super easy.](https://www.youtube.com/watch?v=93BFUD-HAG8&feature=emb_title&scrlybrkr=5670f0b4)  I learned about 
* sketching (shortcut **shift-s**)
* constructions lines (shortcut **Q**)
* dimensions (shortcut **D**)
* extruding both add and remove (shortcut key **E**)
* linear patterns (no shortcut)

Onshape is awesome.  I found it really helpful to rename all my sketches.  It is going to be a GREAT year in engineering.

---


## Mount

### Description
The dimensions are 120 x 120 x 8. there are 5 holes, one in each corner and one in the center. The corner holes are 10 mm, 20 mm from each edge. The center hole is 25 mm and fixed to the origin.

### Evidence
[The Base in Onshape](https://cvilleschools.onshape.com/documents/15bc8dc7b05fb61458cd80d5/w/4e8d4a756d5a2f986cc609e7/e/103b4e6ed8e4690727cbac73)
### Image

<img src="https://github.com/amilste16/basic-cad-deIII/blob/master/images/Screenshot%202020-09-30%20at%201.14.34%20PM.png" alt="The Base" width="300">\

### Reflection

This is my second part, I really flew through it.
* variables
* linear patterns (no shortcut)

---


## Fork

### Description

### Evidence

### Image

<img src="https://github.com/amilste16/basic-cad-deIII/blob/master/images/Screenshot%202020-09-30%20at%201.14.26%20PM.png" alt="The Base" width="300">

### Reflection

This was my third part and it was a little more complicated. The circular base has a diameter of 80 mm and a width of 8 mm. the prongs are 40 x 5 x 75 and are 15 mm from the origin. The circular tube is made of concentric rings (15 mm and 20 mm) and is 60 mm tall.
* chamfer
* fillet
---


## Tire

### Description

### Evidence

### Image

<img src="https://github.com/amilste16/basic-cad-deIII/blob/master/images/Screenshot%202020-09-30%20at%201.14.18%20PM.png" alt="The Base" width="300">

### Reflection

---


## Wheel

### Description

### Evidence

### Image

### Reflection

---


## AxleCollarBearings

### Description

### Evidence

### Image

<img src="https://github.com/amilste16/basic-cad-deIII/blob/master/images/Screenshot%202020-09-30%20at%201.14.05%20PM.png" alt="The Base" width="300">

### Reflection

---
